---
title: "Defence and Peace Economics"
author: "The Defence Economist"
format: dashboard
server: shiny
---

```{r}
#| context: setup
library(shiny)
library(reactable)
library(shinyWidgets)

```

```{r}
dpe_themes <- jsonlite::read_json("../../data/dpe_themes.json") |>
  purrr::flatten() |>
  purrr::map_chr(~.x$theme)

```

# {.sidebar}

```{r}
shinyWidgets:::html_dependency_picker_bs(theme = bslib::bs_theme(version = 5))
tags$br()
shinyWidgets::pickerInput(
  inputId = "theme",
  label = "Theme",
  choices  = dpe_themes,
  multiple = TRUE,
  options = pickerOptions(
    container = "body", 
    selectedTextFormat = "count > 1",
    actionsBox = TRUE
    )
)

```

# Table

```{r}
uiOutput("reactable_ui")
```


```{r}
#| context: server
dpe_detail_df <- readr::read_csv(
  "../../data/2024_35_1_results.csv",
  show_col_types = FALSE
)

dpe_meta_df <- readr::read_csv(
  "../../data/defpea_repec.csv",
  show_col_types = FALSE
)

dpe_df <- dpe_detail_df |>
  dplyr::left_join(dpe_meta_df, 
                   by = c("doi" = "X-DOI"))



dataset <- reactive({
  
  dpe_df <- dpe_df |>
      dplyr::filter(primary_theme %in% input$theme |
                    secondary_theme %in% input$theme)
  
  list(
    meta = dpe_df |>
      dplyr::select(
        "Title", "Author-Name", "Year", "Pages", "Issue", "Volume", "File-URL"
        ),
     detail = dpe_df |>
      dplyr::select(aims, data, methods, findings, conclusions, primary_theme, secondary_theme)
       )
 
})

row_details <- function(index){
  item <- dataset()$detail[index,]
  tagList(
    div(
      style = "padding-left: 40px;",
      reactable(item |> dplyr::select(aims, data, methods, findings, conclusions))
    ),
    div(
      tags$p(tags$b("Primary Theme: "), item |> dplyr::pull(primary_theme)),
      tags$p(tags$b("Secondary Theme: "), item |> dplyr::pull(secondary_theme))
      
    ))
  
}


output$reactable <- renderReactable({
  reactable(
    data = dataset()$meta |> dplyr::select(-`File-URL`), 
    columns = list(
      Title = colDef(cell = function(value, index){
        url <- dataset()$meta[index, "File-URL"] |> dplyr::pull()
        htmltools::tags$a(href = url, target = "_blank", value)
        }, minWidth = 300)
      ),
    details = row_details
    )
})

output$reactable_ui <- renderUI({
  div(class = "dpe-articles",
  h2(class = "title", "Articles"),
  reactableOutput("reactable")
)
})

```